name: Docker Image CI

on:
  push:
    branches:
      - task/UI-1062
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download DM patch
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: ultraio/eosio
        tag: '2.0.9-1.13.0-dm'
        path: /tmp/
        file:  eosio-2.0.9-1.13.0-dm.deb
        token: '${{ secrets.DEVOPS_SECRET }}'

    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=VERSION::$([[ $GITHUB_REF =~ "refs/tags" ]] && echo ${GITHUB_REF#refs/tags/} || echo "${GITHUB_SHA:0:7}")
    - name: Build the Docker image
      run: |
        docker build . -t ultraio/dfuse-eosio:latest -t ultrai/dfuse-eosio:${{ steps.branch_name.outputs.VERSION }}
        # docker push       ultraio/dfuse-eosio:latest
        # echo ${{ secrets.docker_hub_token }} | docker login -u ${{ secrets.docker_hub_username }} --password-stdin
        # docker image tag ultraio/dfuse-eosio:latest ultraio/dfuse-eosio:latest
        # docker image tag ultraio/dfuse-eosio:latest ultraio/dfuse-eosio:${{ steps.branch_name.outputs.VERSION }}
        # docker push      ultraio/dfuse-eosio:latest
        # docker push      ultraio/dfuse-eosio:${{ steps.branch_name.outputs.VERSION }}


